from building3d.geom.numba.types import PointType, IndexType
from building3d.geom.numba.polygon import Polygon
from building3d.geom.numba.mesh import vstack_mesh


def get_mesh_from_polygons(polys: list[Polygon]) -> tuple[PointType, IndexType]:
    """Get vertices and faces of this wall's polygons.

    This function returns faces generated by the ear-clipping algorithm.

    Args:
        polys: list of Polygon instances

    Return:
        tuple of vertices, shaped (num_pts, 3), and faces, shaped (num_tri, 3)
    """
    t_pts = tuple(p.pts for p in polys)
    t_tri = tuple(p.tri for p in polys)
    return vstack_mesh(t_pts, t_tri)
