from building3d.geom.numba.types import PointType, IndexType
from building3d.geom.numba.zone import Zone
from building3d.geom.numba.mesh import vstack_mesh


def get_mesh_from_zones(zones: list[Zone]) -> tuple[PointType, IndexType]:
    """Get vertices and faces of this building's zones.

    This function returns faces generated by the ear-clipping algorithm.

    Args:
        zones: list of Zone instances

    Return:
        tuple of vertices, shaped (num_pts, 3), and faces, shaped (num_tri, 3)
    """
    object_meshes = tuple(z.get_mesh() for z in zones)
    t_pts = tuple(msh[0] for msh in object_meshes)
    t_tri = tuple(msh[1] for msh in object_meshes)
    return vstack_mesh(t_pts, t_tri)
